language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install

script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php test
  - vendor/bin/phpcs --standard=psr2 src/ test/ -n