build: false

environment:
  matrix:
    - PHP_VERSION: 7.1
      VC_VERSION: 14
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VERSION: 7.2
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VERSION: 7.3
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - PHP_VERSION: 7.4
      VC_VERSION: 15
      BUILD_TYPE: nts-Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

  PHP_AVM: https://raw.githubusercontent.com/loilo/php-appveyor/php71-eol/php-appveyor.psm1

cache:
  - 'C:\Downloads -> .appveyor.yml'

platform:
  - x64

install:
  - ps: (new-object Net.WebClient).DownloadString($Env:PHP_AVM) | iex
  - ps: InstallPhp        $Env:PHP_VERSION $Env:BUILD_TYPE $Env:VC_VERSION $Env:PLATFORM
  - ps: InstallComposer
  - ps: $env:Path += ";C:\php"
  - ps: >-
      EnablePhpExtension `
        -Name       openssl
  - ps: >-
      EnablePhpExtension `
        -Name       mbstring

before_test:
  - composer update --no-progress --profile -n
  - composer show

test_script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php test
  - vendor/bin/phpcs --standard=psr2 src/ test/ -n