name: Test CI

on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-version: ['7.3', '7.4', '8.0']

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
      - run: composer install
      - run: vendor/bin/phpunit --bootstrap vendor/autoload.php test
      - run: vendor/bin/phpcs --standard=psr2 src/ test/ -n
